const express=require("express")
const dotenv = require('dotenv')
const helmet = require('helmet')
const cookieParser = require('cookie-parser')
const connectDB = require("./config/db")
const cors=require("cors")
const app = express()
const routerUtilisateur = require('./routes/routeAuthentificationUtilisateur')
const routerService = require("./routes/routeService")
const routerVisite = require("./routes/routeVisite")
const routerClient = require("./routes/routeClient")
const routerEspace = require("./routes/routeEspace")
const routerLivre = require("./routes/routeLivre")
const routerDemande = require("./routes/routeDemande")
dotenv.config()
app.use(helmet())
app.use(express.json())
app.use(cors({origin:process.env.CLIENT_URI,credentials:true}))
app.use(cookieParser())

connectDB()
app.use('/utilisateur',routerUtilisateur)
app.use('/service',routerService)
app.use('/visite',routerVisite)
app.use('/client',routerClient)
app.use('/espace',routerEspace)
app.use('/livre',routerLivre)
app.use('/demandes',routerDemande)




app.listen(process.env.PORT || 3000 ,()=>{
    console.log(`Le serveur tourne !`)
})